# DEFAULT ADDRESSES
LOCALHOST = 'localhost'
DEFAULT_SERVER_ADDRESS = "127.0.0.1"
DEFAULT_SERVER_PORT = 65432

#DEFAULT OPERATIONS
UPLOAD = 0
DOWNLOAD = 1


MAX_SIZE_FILE = 100000000 # 100 MB

FIN = 0
OK = 1
ERROR = -1

# DEFAULT TIMEOUT
TIMEOUT = 0.1

# DEFAULT RETRIES
RETRIES = 10
SYN_RETRIES = 3

# DEFAULT FILE PATHS
DEFAULT_SERVER_DIRPATH = "../server_files/"
DEFAULT_CLIENT_DIRPATH = "../client_files/"


#PROTOCOLS
SAW_PROTOCOL = "saw" #Stop and Wait
SR_PROTOCOL = "sr" #Selective Repeat
DEFAULT_PROTOCOL = SAW_PROTOCOL

# WINDOW CONSTANTS
WINDOW_SIZE=4

# ACK CONSTANTS
MAX_REPEATED_ACKS=3

# RETRANSMISSION CONSTANTS
MAX_RETRANSMITS= 5

# PACKET CONSTANTS

PAYLOAD_SIZE = 4087
HEADER_SIZE = 9

PACKET_SIZE = HEADER_SIZE + PAYLOAD_SIZE

# COLOUR CONSTANTS
COLOUR_GREEN = '\033[92m'
COLOUR_BLUE = '\033[94m'
COLOUR_RED = '\033[91m'
COLOUR_END = '\033[0m'

